/**
 * NextWatch — Movie Seed Script
 * Run: node src/seeds/seedMovies.js
 */
require('dotenv').config();
const mongoose = require('mongoose');
const Movie = require('../models/Movie');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/nextwatch';

const movies = [
  { title: 'The Dark Knight', description: 'Batman faces the Joker, a criminal mastermind who wants to plunge Gotham City into anarchy.', genres: ['Action', 'Crime', 'Drama'], contentType: 'movie', rating: 'PG-13', releaseYear: 2008, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg', imdbId: 'tt0468569', averageScore: 9.0, moods: ['Excited', 'Motivated'] },
  { title: 'Mad Max: Fury Road', description: 'In a post-apocalyptic wasteland, Max teams up with Furiosa to flee a tyrant and his army.', genres: ['Action', 'Adventure', 'Sci-Fi'], contentType: 'movie', rating: 'R', releaseYear: 2015, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg', imdbId: 'tt1392190', averageScore: 8.1, moods: ['Excited', 'Motivated'] },
  { title: 'John Wick', description: 'An ex-hitman comes out of retirement to track down the gangsters who killed his dog.', genres: ['Action', 'Crime', 'Thriller'], contentType: 'movie', rating: 'R', releaseYear: 2014, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg', imdbId: 'tt2911666', averageScore: 7.4, moods: ['Excited', 'Motivated'] },
  { title: 'Top Gun: Maverick', description: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator.', genres: ['Action', 'Drama'], contentType: 'movie', rating: 'PG-13', releaseYear: 2022, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/62HCnUTHJl-hsoGyzAiQC41D3j1.jpg', imdbId: 'tt1745960', averageScore: 8.3, moods: ['Excited', 'Motivated', 'Happy'] },
  { title: 'Mission Impossible Fallout', description: 'Ethan Hunt and his IMF team race against time after a mission gone wrong.', genres: ['Action', 'Adventure', 'Thriller'], contentType: 'movie', rating: 'PG-13', releaseYear: 2018, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg', imdbId: 'tt4912910', averageScore: 7.7, moods: ['Excited', 'Motivated'] },
  { title: 'Inception', description: 'A thief who enters the dreams of others is given a chance to have his criminal record erased.', genres: ['Sci-Fi', 'Action', 'Thriller'], contentType: 'movie', rating: 'PG-13', releaseYear: 2010, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg', imdbId: 'tt1375666', averageScore: 8.8, moods: ['Excited', 'Bored'] },
  { title: 'Interstellar', description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity survival.', genres: ['Sci-Fi', 'Drama', 'Adventure'], contentType: 'movie', rating: 'PG-13', releaseYear: 2014, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', imdbId: 'tt0816692', averageScore: 8.6, moods: ['Excited', 'Nostalgic', 'Motivated'] },
  { title: 'The Matrix', description: 'A computer hacker learns about the true nature of reality and his role in the war against its controllers.', genres: ['Sci-Fi', 'Action'], contentType: 'movie', rating: 'R', releaseYear: 1999, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', imdbId: 'tt0133093', averageScore: 8.7, moods: ['Excited', 'Bored', 'Motivated'] },
  { title: 'Arrival', description: 'A linguist works with the military to communicate with alien lifeforms after mysterious spacecraft appear.', genres: ['Sci-Fi', 'Drama', 'Mystery'], contentType: 'movie', rating: 'PG-13', releaseYear: 2016, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg', imdbId: 'tt2543164', averageScore: 7.9, moods: ['Relaxed', 'Sad'] },
  { title: 'Dune', description: 'A noble family becomes embroiled in a war for control over the galaxy most valuable asset.', genres: ['Sci-Fi', 'Adventure', 'Drama'], contentType: 'movie', rating: 'PG-13', releaseYear: 2021, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/d5NXSklpcvkCMYfNyISXVaZqPm7.jpg', imdbId: 'tt1160419', averageScore: 8.0, moods: ['Excited', 'Motivated'] },
  { title: 'The Shawshank Redemption', description: 'Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.', genres: ['Drama', 'Crime'], contentType: 'movie', rating: 'R', releaseYear: 1994, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', imdbId: 'tt0111161', averageScore: 9.3, moods: ['Sad', 'Motivated', 'Nostalgic'] },
  { title: 'Schindlers List', description: 'Oskar Schindler saves more than a thousand Jewish refugees during the Holocaust.', genres: ['Drama'], contentType: 'movie', rating: 'R', releaseYear: 1993, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', imdbId: 'tt0108052', averageScore: 9.0, moods: ['Sad', 'Motivated'] },
  { title: 'Forrest Gump', description: 'Historical events unfold through the perspective of a kind-hearted Alabama man with a low IQ.', genres: ['Drama', 'Romance', 'Comedy'], contentType: 'movie', rating: 'PG-13', releaseYear: 1994, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg', imdbId: 'tt0109830', averageScore: 8.8, moods: ['Happy', 'Nostalgic', 'Sad'] },
  { title: 'Good Will Hunting', description: 'A janitor at MIT has a gift for mathematics and is discovered by a professor who wants to help him.', genres: ['Drama', 'Romance'], contentType: 'movie', rating: 'R', releaseYear: 1997, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/bABCfKnvCZrY0AAUW1WBNLe1ZGK.jpg', imdbId: 'tt0119217', averageScore: 8.3, moods: ['Motivated', 'Sad'] },
  { title: 'A Beautiful Mind', description: 'A brilliant mathematician accepts secret work in cryptography, then his life takes a turn.', genres: ['Drama', 'Mystery'], contentType: 'movie', rating: 'PG-13', releaseYear: 2001, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/3P52oz9HPQdxwcKFSOobJMFAdcH.jpg', imdbId: 'tt0268978', averageScore: 8.2, moods: ['Motivated', 'Sad'] },
  { title: 'The Grand Budapest Hotel', description: 'A legendary concierge and his lobby boy become embroiled in the theft of a priceless painting.', genres: ['Comedy', 'Drama', 'Adventure'], contentType: 'movie', rating: 'R', releaseYear: 2014, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JiAQf6dYlEtKyJTb.jpg', imdbId: 'tt2278388', averageScore: 8.1, moods: ['Happy', 'Bored'] },
  { title: 'Superbad', description: 'Two co-dependent high school seniors set out to have the best summer before college.', genres: ['Comedy'], contentType: 'movie', rating: 'R', releaseYear: 2007, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg', imdbId: 'tt0829482', averageScore: 7.6, moods: ['Happy', 'Bored'] },
  { title: 'The Hangover', description: 'Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night.', genres: ['Comedy'], contentType: 'movie', rating: 'R', releaseYear: 2009, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/uluhlXubGu1VxU63X9VHCLWDAYP.jpg', imdbId: 'tt1119646', averageScore: 7.7, moods: ['Happy', 'Bored'] },
  { title: 'Knives Out', description: 'A detective investigates the death of a patriarch of an eccentric, combative family.', genres: ['Comedy', 'Crime', 'Drama'], contentType: 'movie', rating: 'PG-13', releaseYear: 2019, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/pThyQovXQrpS2YrqgsxVVpEIREo.jpg', imdbId: 'tt8946378', averageScore: 7.9, moods: ['Happy', 'Bored', 'Excited'] },
  { title: 'About Time', description: 'A young man with the ability to time travel tries to change his past while appreciating the present.', genres: ['Comedy', 'Drama', 'Romance'], contentType: 'movie', rating: 'R', releaseYear: 2013, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/n8ieKQTKSP7bC9Sqhe2SKywtFjb.jpg', imdbId: 'tt2194499', averageScore: 7.8, moods: ['Happy', 'Romantic', 'Nostalgic'] },
  { title: 'La La Land', description: 'A jazz musician and an aspiring actress fall in love while chasing their Hollywood dreams.', genres: ['Romance', 'Drama'], contentType: 'movie', rating: 'PG-13', releaseYear: 2016, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg', imdbId: 'tt3783958', averageScore: 8.0, moods: ['Romantic', 'Sad', 'Happy'] },
  { title: 'Pride and Prejudice', description: 'Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy.', genres: ['Romance', 'Drama'], contentType: 'movie', rating: 'PG', releaseYear: 2005, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/bUe0DIeBMJAkGmKJGdB7t4JBNHJ.jpg', imdbId: 'tt0414387', averageScore: 7.8, moods: ['Romantic', 'Happy'] },
  { title: 'The Notebook', description: 'A poor yet passionate young man falls in love with a rich young woman.', genres: ['Romance', 'Drama'], contentType: 'movie', rating: 'PG-13', releaseYear: 2004, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/qom1SZSENdmHFNZBXbtLAGselxk.jpg', imdbId: 'tt0332280', averageScore: 7.8, moods: ['Romantic', 'Sad'] },
  { title: 'Crazy Stupid Love', description: 'A middle-aged man receives life and romantic advice from a much younger man.', genres: ['Romance', 'Comedy', 'Drama'], contentType: 'movie', rating: 'PG-13', releaseYear: 2011, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/hpOoTCUhCRsGMXxBgDGHEd3jjXl.jpg', imdbId: 'tt1570728', averageScore: 7.4, moods: ['Romantic', 'Happy'] },
  { title: 'Get Out', description: 'A young African-American man visits his white girlfriend parents for the weekend where unsettling secrets emerge.', genres: ['Horror', 'Mystery', 'Thriller'], contentType: 'movie', rating: 'R', releaseYear: 2017, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/qbaHXMCETSiHqWbYjp1SHm1ehiS.jpg', imdbId: 'tt5052448', averageScore: 7.7, moods: ['Scared', 'Excited'] },
  { title: 'Hereditary', description: 'A grieving family is haunted by tragic and disturbing occurrences after the death of their grandmother.', genres: ['Horror', 'Drama', 'Mystery'], contentType: 'movie', rating: 'R', releaseYear: 2018, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/p98BYKC9JCm9jXApkIZbzTFYS7H.jpg', imdbId: 'tt7784604', averageScore: 7.3, moods: ['Scared'] },
  { title: 'A Quiet Place', description: 'A family is forced to live in near silence while hiding from creatures that hunt by sound.', genres: ['Horror', 'Sci-Fi', 'Drama'], contentType: 'movie', rating: 'PG-13', releaseYear: 2018, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg', imdbId: 'tt6644200', averageScore: 7.5, moods: ['Scared', 'Excited'] },
  { title: 'Parasite', description: 'Greed and class discrimination threaten the symbiotic relationship between the wealthy Parks and destitute Kims.', genres: ['Thriller', 'Drama', 'Comedy'], contentType: 'movie', rating: 'R', releaseYear: 2019, language: 'ko', posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', imdbId: 'tt6751668', averageScore: 8.5, moods: ['Scared', 'Excited', 'Bored'] },
  { title: 'Prisoners', description: 'When two daughters go missing, a desperate father takes matters into his own hands.', genres: ['Thriller', 'Crime', 'Drama'], contentType: 'movie', rating: 'R', releaseYear: 2013, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/iLBOeRLMFbP8RJfHoFJrM9TqiSA.jpg', imdbId: 'tt1392214', averageScore: 8.1, moods: ['Scared', 'Excited'] },
  { title: 'Spirited Away', description: 'A 10-year-old girl wanders into a world ruled by gods, witches, and spirits during her family move.', genres: ['Animation', 'Adventure', 'Fantasy'], contentType: 'movie', rating: 'PG', releaseYear: 2001, language: 'ja', posterUrl: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', imdbId: 'tt0245429', averageScore: 8.6, moods: ['Happy', 'Relaxed', 'Nostalgic'] },
  { title: 'The Lion King', description: 'Lion prince Simba is betrayed by his uncle Scar who wants to rule the Pride Lands.', genres: ['Animation', 'Adventure', 'Drama'], contentType: 'movie', rating: 'G', releaseYear: 1994, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg', imdbId: 'tt0110357', averageScore: 8.5, moods: ['Happy', 'Sad', 'Nostalgic'] },
  { title: 'Your Name', description: 'Two strangers find themselves linked in a bizarre way when they discover they swap bodies.', genres: ['Animation', 'Romance', 'Drama'], contentType: 'movie', rating: 'PG', releaseYear: 2016, language: 'ja', posterUrl: 'https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg', imdbId: 'tt5311514', averageScore: 8.4, moods: ['Romantic', 'Sad', 'Happy'] },
  { title: 'Inside Out', description: 'After young Riley is moved to San Francisco, her emotions conflict on how best to navigate a new city.', genres: ['Animation', 'Adventure', 'Comedy'], contentType: 'movie', rating: 'PG', releaseYear: 2015, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/aAmfIX3TT40zUHGcCKrlOZRKC7u.jpg', imdbId: 'tt2096673', averageScore: 8.1, moods: ['Happy', 'Sad'] },
  { title: 'Spider-Man Into the Spider-Verse', description: 'Teen Miles Morales becomes Spider-Man and must join five spider-powered individuals from other dimensions.', genres: ['Animation', 'Action', 'Adventure'], contentType: 'movie', rating: 'PG', releaseYear: 2018, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg', imdbId: 'tt4633694', averageScore: 8.4, moods: ['Happy', 'Excited', 'Motivated'] },
  { title: 'Free Solo', description: 'Follow Alex Honnold as he attempts to become the first person to free solo climb El Capitan.', genres: ['Documentary', 'Adventure'], contentType: 'documentary', rating: 'PG-13', releaseYear: 2018, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/zzlMYmCJ6kJGdgWEWPoJGWftbsU.jpg', imdbId: 'tt7775622', averageScore: 8.2, moods: ['Motivated', 'Excited', 'Relaxed'] },
  { title: 'Our Planet', description: 'David Attenborough presents the never-before-seen natural wonders of our world in stunning detail.', genres: ['Documentary'], contentType: 'documentary', rating: 'TV-PG', releaseYear: 2019, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/lMoEpgBLSF2b8KSHFqLiV6hgB2P.jpg', imdbId: 'tt9253866', averageScore: 9.3, moods: ['Relaxed', 'Happy'] },
  { title: 'Gone Girl', description: 'On his fifth wedding anniversary, Nick Dunne reports that his wife has gone missing.', genres: ['Mystery', 'Drama', 'Thriller'], contentType: 'movie', rating: 'R', releaseYear: 2014, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg', imdbId: 'tt2267998', averageScore: 8.1, moods: ['Scared', 'Excited'] },
  { title: 'Shutter Island', description: 'A U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.', genres: ['Mystery', 'Thriller', 'Drama'], contentType: 'movie', rating: 'R', releaseYear: 2010, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg', imdbId: 'tt1130884', averageScore: 8.1, moods: ['Scared', 'Excited'] },
  { title: 'The Lord of the Rings Fellowship of the Ring', description: 'A meek Hobbit and eight companions set out on a journey to destroy the powerful One Ring.', genres: ['Fantasy', 'Adventure', 'Drama'], contentType: 'movie', rating: 'PG-13', releaseYear: 2001, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', imdbId: 'tt0120737', averageScore: 8.8, moods: ['Excited', 'Nostalgic', 'Motivated'] },
  { title: 'Harry Potter and the Sorcerers Stone', description: 'An orphaned boy enrolls in a school of wizardry and learns the truth about himself and his family.', genres: ['Fantasy', 'Adventure'], contentType: 'movie', rating: 'PG', releaseYear: 2001, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg', imdbId: 'tt0241527', averageScore: 7.6, moods: ['Happy', 'Excited', 'Nostalgic'] },
  { title: 'Pans Labyrinth', description: 'In 1944 Spain, a young girl escapes into an eerie but captivating fantasy world.', genres: ['Fantasy', 'Drama', 'Horror'], contentType: 'movie', rating: 'R', releaseYear: 2006, language: 'es', posterUrl: 'https://image.tmdb.org/t/p/w500/htuhkSk1KBbO6TzDZQwl3F9DFWP.jpg', imdbId: 'tt0457430', averageScore: 8.2, moods: ['Scared', 'Sad'] },
  { title: 'The Godfather', description: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.', genres: ['Crime', 'Drama'], contentType: 'movie', rating: 'R', releaseYear: 1972, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLeBHka4eKgm.jpg', imdbId: 'tt0068646', averageScore: 9.2, moods: ['Excited', 'Nostalgic'] },
  { title: 'Pulp Fiction', description: 'The lives of two mob hitmen, a boxer, and a gangster intertwine in four tales of violence and redemption.', genres: ['Crime', 'Drama'], contentType: 'movie', rating: 'R', releaseYear: 1994, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', imdbId: 'tt0110912', averageScore: 8.9, moods: ['Excited', 'Bored', 'Nostalgic'] },
  { title: 'Goodfellas', description: 'The story of Henry Hill and his life in the mob, covering his eventual FBI informant status.', genres: ['Crime', 'Drama'], contentType: 'movie', rating: 'R', releaseYear: 1990, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg', imdbId: 'tt0099685', averageScore: 8.7, moods: ['Excited', 'Nostalgic'] },
  { title: 'No Country for Old Men', description: 'Violence ensues after a hunter stumbles upon a drug deal gone wrong and more than two million dollars.', genres: ['Western', 'Crime', 'Drama'], contentType: 'movie', rating: 'R', releaseYear: 2007, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/c01JBBRpNGPbMGbdRLBj0gFGC55.jpg', imdbId: 'tt0477348', averageScore: 8.1, moods: ['Scared', 'Nostalgic'] },
  { title: 'Django Unchained', description: 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal plantation owner.', genres: ['Western', 'Drama', 'Action'], contentType: 'movie', rating: 'R', releaseYear: 2012, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWcKhb.jpg', imdbId: 'tt1853728', averageScore: 8.4, moods: ['Excited', 'Motivated'] },
  { title: 'Breaking Bad', description: 'A chemistry teacher diagnosed with cancer turns to manufacturing and selling meth with a former student.', genres: ['Crime', 'Drama', 'Thriller'], contentType: 'tvshow', rating: 'TV-MA', releaseYear: 2008, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg', imdbId: 'tt0903747', averageScore: 9.5, moods: ['Excited', 'Scared', 'Motivated'] },
  { title: 'Stranger Things', description: 'When a young boy disappears, his mother and friends investigate supernatural forces and secret government experiments.', genres: ['Sci-Fi', 'Horror', 'Mystery'], contentType: 'tvshow', rating: 'TV-14', releaseYear: 2016, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg', imdbId: 'tt4574334', averageScore: 8.7, moods: ['Scared', 'Excited', 'Nostalgic'] },
  { title: 'Attack on Titan', description: 'After his hometown is destroyed, Eren Yeager vows to cleanse the earth of giant humanoid Titans.', genres: ['Animation', 'Action', 'Fantasy'], contentType: 'anime', rating: 'TV-MA', releaseYear: 2013, language: 'ja', posterUrl: 'https://image.tmdb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg', imdbId: 'tt2560140', averageScore: 9.0, moods: ['Excited', 'Scared', 'Motivated'] },
  { title: 'The Office', description: 'A mockumentary on a group of typical office workers where the workday consists of ego clashes and inappropriate behaviour.', genres: ['Comedy', 'Drama'], contentType: 'tvshow', rating: 'TV-14', releaseYear: 2005, language: 'en', posterUrl: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg', imdbId: 'tt0386676', averageScore: 8.9, moods: ['Happy', 'Bored', 'Relaxed'] },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB:', MONGO_URI);

    const deleted = await Movie.deleteMany({});
    console.log('Cleared', deleted.deletedCount, 'existing movies');

    const inserted = await Movie.insertMany(movies, { ordered: false });
    console.log('Seeded', inserted.length, 'movies successfully');

    const moodMap = {};
    movies.forEach(m => m.moods.forEach(mood => { moodMap[mood] = (moodMap[mood] || 0) + 1; }));
    console.log('\nMovies per mood:');
    Object.entries(moodMap).sort((a, b) => b[1] - a[1]).forEach(([mood, count]) => {
      console.log(' ', mood.padEnd(12), '->', count, 'movies');
    });

    console.log('\nSeeding complete!');
    process.exit(0);
  } catch (err) {
    if (err.name === 'BulkWriteError') {
      console.warn('Some movies skipped (duplicate imdbId). Seeding complete.');
      process.exit(0);
    }
    console.error('Seed error:', err.message);
    process.exit(1);
  }
}

seed();
